# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lc_classification',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
