# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161122_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lc_classification',
            field=models.CharField(max_length=255),
        ),
    ]
